### ISSUE TITLE
How to parse keyframe data

### ISSUE THREAD

**Issue by shrx** [EloGank/lol-replay-downloader#7]
Is it possible to decode the whole keyframe data to a readable text? You only provide an example to parse a specific string (`"Turret_T1"` or `"Turret_T2"`). How to parse the whole data dump?

**Comment by Divi** [comment]
You can't. The decoded file is a binary file used by the client. You have to parse each byte to retrieve your data. The example of turret is easy, because the string `Turret_Tx` is clear (like the players nickname or champion name).

I advise you to read this wiki : https://github.com/loldevs/leaguespec/wiki/Keyframe-Specification  
It can be outdated.
